[workspace]
members = [
	"rise",
]
exclude = [
]

resolver = "2"

[profile.release]
lto = true
opt-level = 2

[profile.dev]
lto = false
opt-level = 0

#[patch.crates-io]
#z3 = { git = "https://github.com/kui8shi/z3.rs.git"}
#z3 = { path = "../../src/z3.rs" }
