[package]
name = "rise"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "*"
log = "*"
owning_ref = "0.4.1"
quick_cache = "*"
rzapi = { path = "../rzapi" }
thiserror = "*"
z3 = "*"

[dev-dependencies]
serde_json = "1.0.115"
